config/routes.rb
Rails.application.routes.draw do
  root 'researches#index'
  resources :researches
end

app/models/algorithm.rb
class Algorithm < ApplicationRecord
  has_many :researches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/research.rb
class Research < ApplicationRecord
  belongs_to :algorithm
  mount_uploader :result_data, ResultDataUploader
  mount_uploader :languages_file, LanguagesFileUploader

  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
  before_action :set_research, only: %i[show destroy]
  before_action :set_algorithms, only: %i[index new show create]

  def index
    @researches = Research.all
  end

  def new
    @research = Research.new
  end

  def show; end

  def create
    @research = Research.new(research_params)

    if @research.save
      optional_file = "public#{@research.languages_file.url}" if @research.languages_file.url.present?
      filepath = `python3 lib/python_scripts/#{@research.algorithm.code_name} #{optional_file}`.strip
      filename = filepath.split('/').last
      File.open(filepath, 'r') do |f|
        @research.result_data = f
        @research.save
        send_data f.read.force_encoding('BINARY'), filename: filename, type: 'application/pdf', disposition: 'attachment'
      end
      File.delete(filepath)
    else
      render :new, danger: 'Возникла ошибка при создании исследования'
    end
  end

  def destroy
    @research.destroy
    redirect_to researches_path, warning: 'Запись была успешно удалена'
  end

  private

  def set_research
    @research = Research.find(params[:id])
  end

  def set_algorithms
    @algorithms = Algorithm.order(:name)
  end

  def research_params
    params.require(:research).permit(:name, :description, :languages_file, :algorithm_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es-ES">
  <head>
    <title>LanguagesOfTheWorld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to t('common.project'), researches_path, style: "text-decoration: none;", class: "btn text-white h4" %>
        <%= link_to t('researches.new.title'), new_research_path, class: 'btn text-white btn-outline-primary' %>
      </div>
    </nav>
    <br>
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert alert-<%= name %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>

  <footer>
    <div class="container p-2 footer text-center fixed-bottom bg-light">
      © <%= DateTime.now.year %>
      <a class="text-dark" href="https://bitbucket.org/NovartQ/languages_of_the_world">Иванов Артем</a>
    </div>
  </footer>

</html>

app/views/researches/_form.html.erb
<% if @research.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @research.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @research do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :algorithm_id, class: 'form-label' %>
    <%= select_tag "research[algorithm_id]", options_from_collection_for_select(@algorithms, 'id', 'name'), id: 'research_algorithm_id',  class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :languages_file, class: 'form-label'  %>
    <%= f.file_field :languages_file, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit t('common.submit', action: @research.new_record? ? t('common.submit') : t('common.edit')), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/researches/_research.html.erb
<article class="research">
  <section class="research-head">
    <h5><%= link_to research.name, research_path(research) %></h5>
    <p> Описание: <%= research.description %></p> <!--TODO: Make truncated description next -->
    <p> Алгоритм исследования: <%= research.algorithm.name %></p>
    <small>
      <time>
        <%= Russian::strftime(research.created_at, "%d %B, %Y") %></time> |
        <%= link_to t('common.delete'), research_path(research), method: :delete, data: { confirm: t('common.confirmation') } %>
    </small>
  </section>
</article>
<hr>

app/views/researches/index.html.erb
<h3>  <%= t('.title') %> </h3>

<%= render @researches %>

app/views/researches/new.html.erb
<h3> <%= t('.title') %></h3>

<%= render 'form' %>

app/views/researches/show.html.erb
<article class="research">
  <section class="research-head">
    <h4><%= @research.name %></h4>
    <% if @research.description.present? %>
      <p> Описание: <%= @research.description %></p>
    <% end %>
    <p>Алгоритм исследования: <%= @research.algorithm.name %></p>
    <div>
      <p><strong>Скачать:</strong></p>
      <section style="margin-top: 15px;">
        <%= link_to "Результаты", @research.result_data_url, download: @research.result_data_url, target: "_blank", class: "btn btn-outline-primary" %>
        |
        <%= @research.result_data_identifier %>
      </section>
      <% if @research.languages_file.present? %>
        <section style="margin-top: 15px;">
          <%= link_to "Входные данные", @research.languages_file_url, download: @research.languages_file_url, target: "_blank", class: "btn btn-outline-primary" %>
          |
          <%= @research.languages_file_identifier %>
        </section>
      <% end %>


      <hr>
      <small>
        <time><%= Russian::strftime(@research.created_at, "%d %B, %Y") %></time>
        |
        <%= link_to t('common.delete'), research_path(@research), method: :delete, data: { confirm: t('common.confirmation') } %>
      </small>
    </div>
  </section>
</article>